collections:
  - arista.eos
  - arubanetworks.aos_switch
  - arubanetworks.aoscx
  - awx.awx
  - check_point.mgmt
  - cisco.aci
  - cisco.asa
  - cisco.intersight
  - cisco.ios
  - cisco.iosxr
  - cisco.meraki
  - cisco.mso
  - cisco.nso
  - cisco.nxos
  - cisco.ucs
  - cloudscale_ch.cloud
  - community.network.aruba_command
  - community.crypto
  - community.fortios
  - community.general
  - community.mysql
  - community.network
  - community.postgresql
  - community.routeros
  - community.windows
  - f5networks.f5_modules
  - fortinet.fortimanager
  - fortinet.fortios
  - junipernetworks.junos
  - vyos.vyos