collections:
  - arista.eos
  - arubanetworks.aos_switch
  - arubanetworks.aoscx
  - awx.awx
  - check_point.mgmt
  - cisco.aci
  - cisco.asa
  - cisco.intersight
  - cisco.ios
  - cisco.iosxr
  - cisco.meraki
  - cisco.mso
  - cisco.nso
  - cisco.nxos
  - cisco.ucs
  - cloudscale_ch.cloud
  - community.aws
  - community.crypto
  - community.docker
  - community.fortios
  - community.general
  - community.google
  - community.grafana
  - community.kubevirt
  - community.kubernetes
  - community.libvirt
  - community.mongodb
  - community.mysql
  - community.network
  - community.okd
  - community.postgresql
  - community.proxysql
  - community.routeros
  - community.sops
  - community.windows
  - containers.podman
  - f5networks.f5_modules
  - fortinet.fortimanager
  - fortinet.fortios
  - frr.frr
  - hpe.nimble
  - ibm.qradar
  - inspur.sm
  - junipernetworks.junos
  - kubernetes.core
  - splunk.es
  - t_systems_mms.icinga_director
  - vyos.vyos
  - wti.remote