collections:
  - arista.eos
  - arubanetworks.aos_switch
  - arubanetworks.aoscx
  - awx.awx
  - check_point.mgmt
  - cisco.aci
  - cisco.asa
  - cisco.intersight
  - cisco.ios
  - cisco.iosxr
  - cisco.meraki
  - cisco.mso
  - cisco.nso
  - cisco.nxos
  - cisco.ucs
  - cloudscale_ch.cloud
  - community.crypto
  - community.fortios
  - community.general
  - community.mysql
  - community.network
  - community.postgresql
  - community.routeros
  - community.windows
  - f5networks.f5_modules
  - fortinet.fortimanager
  - fortinet.fortios
  - junipernetworks.junos
  - vyos.vyos
  # - community.docker
  # - community.google
  # - community.grafana
  # - community.kubevirt
  # - community.kubernetes
  # - community.libvirt
  # - community.mongodb
  # - community.okd
  # - community.proxysql
  # - community.sops
  # - containers.podman
  # - frr.frr
  # - hpe.nimble
  # - ibm.qradar
  # - inspur.sm
  # - kubernetes.core
  # - splunk.es
  # - t_systems_mms.icinga_director
  # - wti.remote
  # - community.aws